# Generated by Django 5.2 on 2026-09-18 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor_app', '0003_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('visit_date', models.DateField()),
                ('purpose', models.TextField()),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('requested_time', models.TimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitor_app.department')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitor_app.employee')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitor_app.visitor')),
            ],
        ),
    ]
