# Generated by Django 5.2 on 2026-09-18 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor_app', '0004_visitrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='GatePass',
            fields=[
                ('gate_pass_id', models.AutoField(primary_key=True, serialize=False)),
                ('pass_number', models.CharField(max_length=50, unique=True)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('valid_until', models.DateField()),
                ('status', models.CharField(default='Active', max_length=20)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='visitor_app.visitrequest')),
            ],
        ),
    ]
