# Generated by Django 5.2 on 2026-09-18 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor_app', '0005_gatepass'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckInOutLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('gate_pass', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='visitor_app.gatepass')),
            ],
        ),
    ]
